---
- name: Configure Nginx
  hosts: web
  become: true

  tasks:

    - name: Deploy custom Nginx configuration
      copy:
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;

              root /var/www/html;
              index index.html;

              server_name _;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
        backup: true
      notify: Restart Nginx

    - name: Validate Nginx configuration
      command: nginx -t
      changed_when: false

  handlers:

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
