name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  Build-Tag:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6

      # Step 2: Build Docker image
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: my-app:latest
