name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # Step 1: Download repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Build Docker image
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: my-app:latest
