# Goal: Create an yaml file that reads and print secrets

name: Secrets

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check If Secrets Exits
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret set is: true"
          else
            echo "The secret set is: False"
          fi

      - name: Attempt to print secret
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"


