name: PR Lifecycle

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  pr-events:
    runs-on: ubuntu-latest

    steps:
      - name: Print PR Information
        run: |
          echo "Event Action: ${{ github.event.action }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target Branch: ${{ github.event.pull_request.base.ref }}"

      - name: Run only when PR is merged
        if: github.event.pull_request.merged == true
        run: echo "Pull Request has been merged successfully."
